apiVersion: v1
kind: ServiceAccount
metadata:
  name: tc-ebpf-tracer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tc-ebpf-tracer
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tc-ebpf-tracer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tc-ebpf-tracer
subjects:
- kind: ServiceAccount
  name: tc-ebpf-tracer
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tc-ebpf-tracer
  namespace: default
spec:
  selector:
    matchLabels:
      app: tc-ebpf-tracer
  template:
    metadata:
      labels:
        app: tc-ebpf-tracer
    spec:
      serviceAccountName: tc-ebpf-tracer
      hostNetwork: true
      hostPID: true
      containers:
      - name: tracer
        image: tc-audio-tracer:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - SYS_RESOURCE
            - IPC_LOCK
        volumeMounts:
        - name: output
          mountPath: /output
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
        - name: sys-fs-bpf
          mountPath: /sys/fs/bpf
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: output
        hostPath:
          path: /var/log/audio-tracer
          type: DirectoryOrCreate
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
      - name: sys-fs-bpf
        hostPath:
          path: /sys/fs/bpf
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
---
# Service to view trace output
apiVersion: v1
kind: Service
metadata:
  name: trace-viewer
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30088
  selector:
    app: trace-viewer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-viewer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-viewer
  template:
    metadata:
      labels:
        app: trace-viewer
    spec:
      containers:
      - name: viewer
        image: python:3.11-slim
        command:
        - python
        - -m
        - http.server
        - "8080"
        - --directory
        - /traces
        volumeMounts:
        - name: traces
          mountPath: /traces
      volumes:
      - name: traces
        hostPath:
          path: /var/log/audio-tracer
          type: DirectoryOrCreate